apiVersion: 1

datasources:
  - name: ViaIpe
    type: postgres
    access: proxy
    isDefault: false
    editable: true
    readOnly: false

    url: db_viaipe:5432

    user: postgres
    secureJsonData:
      password: postgres
      
    jsonData:
      database: viaipe_db
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
